# -- Database connection details --
database:
    source:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_source"

    destination:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_store"

# -- AWS connection details --
aws:
    default_region: "ap-southeast-2"
    s3:
        bucket_name: "legal-store"

# List of tables to be read by the connector
tables:
  tables_to_read:
    - database: legal_source
      s3_folder: "case-laws/nt/"
      audit_job_name: "ai_enrichment_service_juriscontent_nt"
      jurisdiction: 'NT'
    - database: legal_source
      s3_folder: "case-laws/tas/"
      audit_job_name: "ai_enrichment_service_juriscontent_tas"
      jurisdiction: 'TAS'
    - database: legal_source
      s3_folder: "case-laws/vic/"
      audit_job_name: "ai_enrichment_service_juriscontent_vic"
      jurisdiction: 'VIC'
    - database: legal_source
      s3_folder: "case-laws/nsw/"
      audit_job_name: "ai_enrichment_service_juriscontent_nsw"
      jurisdiction: 'NSW'
    - database: legal_source
      s3_folder: "case-laws/wa/"
      audit_job_name: "ai_enrichment_service_juriscontent_wa"
      jurisdiction: 'WA'
    - database: legal_source
      s3_folder: "case-laws/sa/"
      audit_job_name: "ai_enrichment_service_juriscontent_sa"
      jurisdiction: 'SA'
    - database: legal_source
      s3_folder: "case-laws/qld/"
      audit_job_name: "ai_enrichment_service_juriscontent_qld"
      jurisdiction: 'QLD'
    - database: legal_source
      s3_folder: "case-laws/act/"
      audit_job_name: "ai_enrichment_service_juriscontent_act"
      jurisdiction: 'ACT'
    - database: legal_source
      s3_folder: "case-laws/commonwealth/"
      audit_job_name: "ai_enrichment_service_juriscontent_commonwealth"
      jurisdiction: 'FED'
  tables_to_write:
    - database: legal_store
      table: caselaw_enrichment_status
      step_columns:
        text_extract:
          status: "status_juriscontent_html"
          duration: "duration_juriscontent_html"
          start_time: "start_time_juriscontent_html"
          end_time: "end_time_juriscontent_html"
  audit_log_table:
    - database: legal_store
      table: audit_log
      job_name: "caselaw juriscontent generation"

# -- File naming conventions for the enrichment service --
enrichment_filenames:
  source_html: "miniviewer.html"
  extracted_html: "juriscontent.html"

# -- Audit log configuration --
audit_log:
  text_extraction_job:
    database: "legal_store"
    table: "audit_log"
    job_name: "caselaw juriscontent generation"

# -- Registry details
tables_registry:
    database: "legal_store"
    table: "caselaw_registry"
    # --- FIX & ADD ---
    # Corrected the duplicate 'column' key and added the new status column
    year_column: "year"
    download_status_column: "status_content_download" 
    # --- END FIX & ADD ---
    processing_years: []
    jurisdiction_codes: []