# config/headless_rules.yaml

# -- Rules for inferring heading tags from styled elements in headless HTML --
# The system will iterate through these rules in order. The first rule that
# a text element matches will determine its heading level.

# -- Base styles help differentiate headings from regular bold text --
base_styles:
  # Elements with a font size below this value (in pixels) will not be considered headings,
  # even if they are bold.
  body_font_size_threshold_px: 15

heading_rules:
  # Rule 1: Identify the main title (H1)
  - level: "h1"
    is_title: true  # Special flag to ensure only the first prominent element becomes the title
    criteria:
      min_font_size_px: 20
      font_weight: "bold"

  # Rule 2: Identify major section headings (H2)
  - level: "h2"
    criteria:
      min_font_size_px: 18
      font_weight: "bold"

  # Rule 3: Identify sub-section headings (H3)
  - level: "h3"
    criteria:
      min_font_size_px: 16
      font_weight: "bold"

  # Rule 4: Identify minor headings (H4)
  - level: "h4"
    criteria:
      min_font_size_px: 15 # Must be equal to or greater than the threshold
      font_weight: "bold"