# -- Google cloud project details --
google_cloud:
    project_id: "juristab"
    region: "us"
    processor_id: "c60807664382dc8" 

# -- Database connection details --
database:
    source:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_source"

    destination:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_store"

#OpenSearch Details
vector_db:
    host: "f4xiu02cfrb0zrwqwob5.ap-southeast-2.aoss.amazonaws.com"
    index_name: "legal-store"
    embedding_dimension: 1024
    default_region: "ap-southeast-2"
    doc_type: "case-law"

# -- AWS connection details --
aws:
    default_region: "ap-southeast-2"
    s3:
        bucket_name: "legal-store"
    
# -- AI model configuration --
models:
    embedding:
        model_name: "BAAI/bge-large-en-v1.5"
        # Using character count as a proxy for tokens. BGE model has a 512 token limit.
        # This chunk size is a safe estimate.
        chunk_size: 1500 
        chunk_overlap: 200

# List of tables to be read by the connector
tables:
  tables_to_read:
    - database: legal_source
      table: l2_scan_jade_io_caselaw_nt
      s3_folder: "case-laws/nt/"
    - database: legal_source
      table: l2_scan_jade_io_caselaw_tas
      s3_folder: "case-laws/tas/"
    - database: legal_source
      table: l2_scan_jade_io_caselaw_vic
      s3_folder: "case-laws/vic/"
    - database: legal_source
      table: l2_scan_jade_io_caselaw_nsw
      s3_folder: "case-laws/nsw/"
    - database: legal_source
      table: l2_scan_jade_io_caselaw_wa
      s3_folder: "case-laws/wa/"
    - database: legal_source
      table: l2_scan_jade_io_caselaw_sa
      s3_folder: "case-laws/sa/"
    - database: legal_source
      table: l2_scan_jade_io_caselaw_qld
      s3_folder: "case-laws/qld/"
    - database: legal_source
      table: l2_scan_jade_io_caselaw_act
      s3_folder: "case-laws/act/"
    - database: legal_source
      table: l2_scan_jade_io_caselaw_commonwealth
      s3_folder: "case-laws/commonwealth/"
      
  tables_to_write:
    - database: legal_store
      table: caselaw_enrichment_status
      columns:
        processing_status: "status_text_embedding"
        processing_duration: "duration_text_embedding"
        start_time: "start_time_text_embedding"
        end_time: "end_time_text_embedding"
        price: "price_text_embedding"

# -- File naming conventions for the enrichment service --
enrichment_filenames:
  source_text: "miniviewer.txt"
  embedding_output: "embeddings.npy"

# -- Registry details
registry:
    # Used for filtering by year and jurisdiction
    caselaw_registry:
        database: "legal_store"
        table: "caselaw_registry"
        year_column: "year"
        jurisdiction_column: "jurisdiction_code"
        processing_years: []
        jurisdiction_codes: ['ACT','VIC','NT','QLD','WA','SA','TAS','FED','NSW']
    
    # Used for the new word count pre-processing check
    caselaw_metadata:
        database: "legal_store"
        table: "caselaw_metadata"
        word_count_column: "count_word"
        word_count_threshold: 5


# -- Server POD price
server_pod_price:
    hour_price: 3.28
