# -- Database connection details --
database:
    source:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_source"

    destination:
        dialect: "mysql"
        driver: "mysqlconnector"
        host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
        port: "3306"
        name: "legal_store"

# List of tables to be read by the connector
tables:
    tables_to_read:
        - database: legal_source
          table: l2_scan_jade_io_legislation_nt
          jurisdiction: NT
          storage_folder: nt
        - database: legal_source
          table: l2_scan_jade_io_legislation_nsw
          jurisdiction: NSW
          storage_folder: nsw
        - database: legal_source
          table: l2_scan_jade_io_legislation_vic
          jurisdiction: VIC
          storage_folder: vic
        - database: legal_source
          table: l2_scan_jade_io_legislation_qld
          jurisdiction: QLD
          storage_folder: qld
        - database: legal_source
          table: l2_scan_jade_io_legislation_tas
          jurisdiction: TAS
          storage_folder: tas
        - database: legal_source
          table: l2_scan_jade_io_legislation_act
          jurisdiction: ACT
          storage_folder: act
        - database: legal_source
          table: l2_scan_jade_io_legislation_commonwealth
          jurisdiction: FED
          storage_folder: commonwealth
        - database: legal_source
          table: l2_scan_jade_io_legislation_sa
          jurisdiction: SA
          storage_folder: sa
        - database: legal_source
          table: l2_scan_jade_io_legislation_wa
          jurisdiction: WA
          storage_folder: wa
    tables_to_write:
      - database: legal_store
        table: legislation_registry

    audit_log_table:
      - database: legal_store
        table: audit_log

# Source file paths
filepath: s3://legal-store/legislation/

#Audit trail log
job_name: legislation_registration
job_id: lr_1

